<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <OutputType>Exe</OutputType>
        <RootNamespace>word_processing_encryption</RootNamespace>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    </PropertyGroup>
    <ItemGroup>
        <None Update="Documents\testEncrypted.docx">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
        <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
        <PackageReference Include="DevExpress.Document.Processor" Version="24.2.*-*" />
    </ItemGroup>
</Project>